Fix/scottish database fields
ScottishParliament/e-petitions pull request #12
Opened 2021-01-21 13:18 UTC by freesteph

This ended up being much more than just the database fields because the corresponding ActiveRecord mappings needs to be updated at the same time. The diff is huge because of a couple of `sed` passes on the application code so I would recommend looking at the commits separately.

The app boots.

2021-01-21 13:21 UTC, pixeltrix commented
Can you convert the .env file as well:

```
COMPOSE_PROJECT_NAME=scottish-petitions
```

https://github.com/ScottishParliament/e-petitions/blob/main/.env

2021-01-21 13:22 UTC, freesteph commented
> Can you convert the .env file as well:
> 
> ```
> COMPOSE_PROJECT_NAME=scottish-petitions
> ```
> 
> https://github.com/ScottishParliament/e-petitions/blob/main/.env

Thanks! Was actually wondering where that identifier lived :smile:

2021-01-21 13:43 UTC, cdccollins approved these changes

2021-01-22 11:27 UTC, pixeltrix requested changes

2021-01-22 11:27 UTC, pixeltrix commented on .github/workflows/preview.yml
> -        APPSIGNAL_APP_NAME: welsh-petitions-preview
This should be `scottish` not `gaelic`

2021-01-22 11:27 UTC, pixeltrix commented on lib/package_builder.rb
> +    ENV.fetch('AWS_PROFILE', 'gaelic-petitions')
This should be `scottish`

2021-01-22 11:27 UTC, pixeltrix commented on lib/package_builder.rb
> +    ENV.fetch('APPSIGNAL_APP_NAME', "gaelic-petitions-#{environment}")
This should be `scottish`

2021-01-22 11:27 UTC, pixeltrix commented on lib/package_builder.rb
> +    "gaelic-petitions-deployments"
This should be `scottish`

2021-01-22 14:58 UTC, merged