doc: update README
ScottishParliament/e-petitions pull request #4
Opened 2021-01-19 15:04 UTC by freesteph

2021-01-19 15:41 UTC, cdccollins approved these changes

2021-01-19 15:43 UTC, pixeltrix requested changes

2021-01-19 15:43 UTC, pixeltrix commented on README.md
> +This is the code base for the Scottish Parliament's petitions service (https://petitions.parliament.scott).
Only one 't' in `.scot`

2021-01-20 00:18 UTC, pixeltrix approved these changes

2021-01-20 09:58 UTC, merged